name: project_aedp
description: "A new Flutter project."
# The following line prevents accidental publication to pub.dev.
publish_to: 'none'

# Application version and build number
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.7
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  meta: ^1.15.0
  crypto: ^3.0.6
  file_picker: any
  flutter_localizations:
    sdk: flutter
  intl: any
  easy_localization: ^3.0.7
  equatable: ^2.0.7
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true
