name: project_aedp
description: "A new Flutter project."
# The following line prevents accidental publication to pub.dev.
publish_to: 'none'

# Application version and build number
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.7
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  meta: ^1.15.0
  crypto: ^3.0.6
  file_picker: any
  flutter_localizations:
    sdk: flutter
  intl: any
  easy_localization: ^3.0.7
  equatable: ^2.0.7
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.4
  bcrypt: ^1.1.3
  http: ^1.2.2
  path_provider: ^2.1.5
  open_file: ^3.5.10
  permission_handler: ^12.0.1
  dio: ^5.7.0
  provider: ^6.1.2
  path: any
  translator: ^1.0.3+1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  intl_utils: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true
